# Generated by Django 5.1 on 2024-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
